github.com:
    users:
        randomTwitch:
            oauth_token: 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
    git_protocol: https
    user: randomTwitch
    oauth_token: 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
